services:

  app:
    build: app
    depends_on:
      - redis-sentinel-1
      - redis-sentinel-2
      - redis-sentinel-3
    networks:
      - redis-network

  redis-master:
    image: redis:7.2.4
    volumes:
      - "./.data:/data"
    networks:
      - redis-network

  redis-slave-1:
    image: redis:7.2.4
    command: redis-server --slaveof redis-master 6379
    networks:
      - redis-network
    volumes:
      - "./.data-slave-1:/data"

  redis-slave-2:
    image: redis:7.2.4
    command: redis-server --slaveof redis-master 6379
    volumes:
      - "./.data-slave-2:/data"
    networks:
      - redis-network

  redis-sentinel-1:
    build:
      context: ./sentinel
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - redis-network

  redis-sentinel-2:
    build:
      context: ./sentinel
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - redis-network

  redis-sentinel-3:
    build:
      context: ./sentinel
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge